version: '3'
services:
  my-app: wakeOnLan
    build:
      context: . # Directorul curent (unde se află Dockerfile și docker-compose.yml)
    container_name: wakeOnLan_container # Nume opțional pentru container