
services:
  # Numele serviciului este 'wakeOnLan'
  wakeOnLan: 
    # Proprietățile serviciului 'wakeOnLan' încep indentate pe linia următoare
    build:
      context: . 
      dockerfile: Dockerfile 
    container_name: wake_on_lan_container # Poți păstra un nume de container specific